# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fakerforge < Formula
  desc "Pull FakerForge synthetic data directly into your local database"
  homepage "https://fakerforge.com/docs/fakerforge-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kwasii1/fakerforge-db-agent/releases/download/v0.2.0/fakerforge_darwin_amd64.tar.gz"
      sha256 "2a3aa47f7e71e5b5843cefd502e37cd1ca4f86e8db4294df5c41434022243db6"

      define_method(:install) do
        bin.install "fakerforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kwasii1/fakerforge-db-agent/releases/download/v0.2.0/fakerforge_darwin_arm64.tar.gz"
      sha256 "dd3cbfd2f47e8605113377308b6550aba1d690b7591b25d30e3849caba58511e"

      define_method(:install) do
        bin.install "fakerforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwasii1/fakerforge-db-agent/releases/download/v0.2.0/fakerforge_linux_amd64.tar.gz"
      sha256 "957addf574530b1fe277e39bf8feadacbee9ae7158d199ebe50645b2cbce8eda"
      define_method(:install) do
        bin.install "fakerforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwasii1/fakerforge-db-agent/releases/download/v0.2.0/fakerforge_linux_arm64.tar.gz"
      sha256 "437bd9ea5480b6232d51577535c7f32765c0af7619521c2825d41ea65802f58e"
      define_method(:install) do
        bin.install "fakerforge"
      end
    end
  end
end
